<template>
	<div class="container">
		<div class="content">
			我是消息页面
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
		</div>
		<v-footer></v-footer>
	</div>
</template>
<script src="./script.js"></script>
<style lang="scss" src="./style.scss"></style>
<!--<style lang="css" src="./../../assets/css/bootstrap.css"></style>-->
<!--<link rel="stylesheet" type="text/css" href="./../assets/css/bootstrap.css" />-->