<template>
	<div class="container">
		<!--<v-header></v-header>-->
		<div class="content">
			发送页面
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
			<h1>lala </h1>
		</div>
	</div>
</template>
<script src="./script.js"></script>
<style lang="scss" src="./style.scss"></style>
<!--<style lang="css" src="./../../assets/css/bootstrap.css"></style>-->
<!--<link rel="stylesheet" type="text/css" href="./../assets/css/bootstrap.css" />-->